#
#  Author: Hari Sekhon
#  Date: [% DATE # 2020-02-11 12:53:33 +0000 (Tue, 11 Feb 2020) %]

substitutions:
  _FF:  faceforensics
  _RE:  reverse
  _API: api
  _KIO: kerasio
  _RUI: reactui
  _CH: cache

  _SRV_FF:  faceforensics
  _SRV_RE:  reverse
  _SRV_API: api
  _SRV_KIO: kerasio
  _SRV_RUI: reactui
  _SRV_CH:  cache

  _REGISTRY: gcr.io
  _PROJECT: $PROJECT_ID
  _REGION: europe-west1

timeout: 3660s

steps:
# ============================================================================ #
#                      API
# ============================================================================ #

# Run test
- id: test-api
  name: 'golang'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      cd api; go test -v ./tests

# Build container
- id: build-api
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cd api \
      docker build . -t ${_REGISTRY}/${_PROJECT}/${_API}

# Deploy
- id: deploy-api
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
   - 'run'
   - 'deploy'
   - '${_SRV_API}'
   - '--image'
   - '${_REGISTRY}/${_PROJECT}/${_API}'
   - '--region'
   - '${_REGION}'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated' 

# ============================================================================ #
#                      CACHE
# ============================================================================ #

# Pull image from cache
- id: pull-image-ch
  name: gcr.io/cloud-builders/docker
  waitFor: [ '-' ]  # don't wait for any other steps
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull ${_REGISTRY}/${_PROJECT}/${_CH} || exit 0

# Run test
- id: test-ch
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker run -entrypoint=/bin/bash -v `pwd`/cache:/app ${_REGISTRY}/${_PROJECT}/${_CH} python tests.py

# Build container
- id: build-ff
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cd cache \
      docker build . -t ${_REGISTRY}/${_PROJECT}/${_CH} --cache-from=${_REGISTRY}/${_PROJECT}/${_CH}

# Deploy
- id: deploy-ch
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
   - 'run'
   - 'deploy'
   - '${_SRV_CH}'
   - '--image'
   - '${_REGISTRY}/${_PROJECT}/${_CH}'
   - '--region'
   - '${_REGION}'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated' 