#
#  Author: Hari Sekhon
#  Date: [% DATE # 2020-02-11 12:53:33 +0000 (Tue, 11 Feb 2020) %]

substitutions:
  _FF:  faceforensics
  _RE:  reverse
  _API: api
  _KIO: kerasio
  _RUI: reactui
  _CH: cache

  _SRV_FF:  faceforensics
  _SRV_RE:  reverse
  _SRV_API: api
  _SRV_KIO: kerasio
  _SRV_RUI: reactui
  _SRV_CH:  cache

  _REGISTRY: gcr.io
  _PROJECT: $PROJECT_ID
  _REGION: europe-west1

timeout: 3660s

steps:
# ============================================================================ #
#                      FACEFORENSICS++
# ============================================================================ #

# Pull image from cache
- id: pull-image-ff
  name: gcr.io/cloud-builders/docker
  waitFor: [ '-' ]  # don't wait for any other steps
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull ${_REGISTRY}/${_PROJECT}/${_FF} || exit 0

# Run test
- id: test-ff
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker run -entrypoint=/bin/bash -v `pwd`/faceforensics:/app ${_REGISTRY}/${_PROJECT}/${_FF} python tests.py

# Push container
- id: push-ff
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker push ${_REGISTRY}/${_PROJECT}/${_FF}

# Build container
- id: build-ff
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build ./faceforensics -t ${_REGISTRY}/${_PROJECT}/${_FF} --cache-from=${_REGISTRY}/${_PROJECT}/${_FF}

# Deploy
- id: deploy-ff
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
   - 'run'
   - 'deploy'
   - '${_SRV_FF}'
   - '--image'
   - '${_REGISTRY}/${_PROJECT}/${_FF}'
   - '--region'
   - '${_REGION}'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated' 

# ============================================================================ #
#                      KERAS
# ============================================================================ #

# Pull image from cache
- id: pull-image-kio
  name: gcr.io/cloud-builders/docker
  waitFor: [ '-' ]  # don't wait for any other steps
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull ${_REGISTRY}/${_PROJECT}/${_KIO} || exit 0

# Run test
- id: test-kio
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker run -entrypoint=/bin/bash -v `pwd`/kerasio:/app ${_REGISTRY}/${_PROJECT}/${_KIO} python tests.py

# Build container
- id: build-kio
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build ./kerasio -t ${_REGISTRY}/${_PROJECT}/${_KIO} --cache-from=${_REGISTRY}/${_PROJECT}/${_KIO}

# Push container
- id: push-kio
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker push ${_REGISTRY}/${_PROJECT}/${_KIO}

# Deploy
- id: deploy-kio
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
   - 'run'
   - 'deploy'
   - '${_SRV_KIO}'
   - '--image'
   - '${_REGISTRY}/${_PROJECT}/${_KIO}'
   - '--region'
   - '${_REGION}'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated' 

# ============================================================================ #
#                      REVERSE ENGINEERING
# ============================================================================ #

# Pull image from cache
- id: pull-image-re
  name: gcr.io/cloud-builders/docker
  waitFor: [ '-' ]  # don't wait for any other steps
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull ${_REGISTRY}/${_PROJECT}/${_RE} || exit 0

# Run test
- id: test-re
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker run -entrypoint=/bin/bash -v `pwd`/reverse-eng/src:/app/src ${_REGISTRY}/${_PROJECT}/${_RE} python tests.py

# Build container
- id: build-re
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build ./reverse-eng -t ${_REGISTRY}/${_PROJECT}/${_RE} --cache-from=${_REGISTRY}/${_PROJECT}/${_RE}

# Push container
- id: push-re
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker push ${_REGISTRY}/${_PROJECT}/${_RE}

# Deploy
- id: deploy-re
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
   - 'run'
   - 'deploy'
   - '${_SRV_RE}'
   - '--image'
   - '${_REGISTRY}/${_PROJECT}/${_RE}'
   - '--region'
   - '${_REGION}'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated' 

# ============================================================================ #
#                      API
# ============================================================================ #

# Run test
- id: test-api
  name: 'golang'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      cd api; go test -v ./tests

# Build container
- id: build-api
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build ./api -t ${_REGISTRY}/${_PROJECT}/${_API}

# Push container
- id: push-api
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker push ${_REGISTRY}/${_PROJECT}/${_API}

# Deploy
- id: deploy-api
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
   - 'run'
   - 'deploy'
   - '${_SRV_API}'
   - '--image'
   - '${_REGISTRY}/${_PROJECT}/${_API}'
   - '--region'
   - '${_REGION}'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated' 

# ============================================================================ #
#                      CACHE
# ============================================================================ #

# Pull image from cache
- id: pull-image-ch
  name: gcr.io/cloud-builders/docker
  waitFor: [ '-' ]  # don't wait for any other steps
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull ${_REGISTRY}/${_PROJECT}/${_CH} || exit 0

# Run test
- id: test-ch
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker run -entrypoint=/bin/bash -v `pwd`/cache:/app ${_REGISTRY}/${_PROJECT}/${_CH} python tests.py

# Build container
- id: build-ch
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build ./cache -t ${_REGISTRY}/${_PROJECT}/${_CH} --cache-from=${_REGISTRY}/${_PROJECT}/${_CH}

# Push container
- id: push-ch
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker push ${_REGISTRY}/${_PROJECT}/${_CH}

# Deploy
- id: deploy-ch
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
   - 'run'
   - 'deploy'
   - '${_SRV_CH}'
   - '--image'
   - '${_REGISTRY}/${_PROJECT}/${_CH}'
   - '--region'
   - '${_REGION}'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated' 


# ============================================================================ #
#                      REACT
# ============================================================================ #

# Build container
- id: build-rui
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build ./react-ui -t ${_REGISTRY}/${_PROJECT}/${_RUI}

# Push container
- id: push-rui
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker push ${_REGISTRY}/${_PROJECT}/${_RUI}

# Deploy
- id: deploy-rui
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
   - 'run'
   - 'deploy'
   - '${_SRV_RUI}'
   - '--image'
   - '${_REGISTRY}/${_PROJECT}/${_RUI}'
   - '--region'
   - '${_REGION}'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated' 